import React from "react";
import ElectricPageTemplate from "./ElectricPageTemplate";
import depannageImage from "../assets/pic3.webp";

const depannageFaqData = [
  {
    title: "Dépannages électrique avec Elewatt",
    content: "Le dépannage électrique est un service indispensable pour tout propriétaire de maison ou d'entreprise. Les pannes de courant peuvent causer des désagréments importants, qu'il s'agisse d'une panne de courant complète ou partielle. Si vous rencontrez des problèmes électriques, il est important de faire appel à un électricien professionnel pour résoudre rapidement et efficacement les problèmes. Nos électriciens expérimentés utilisent les dernières technologies pour diagnostiquer et réparer rapidement les problèmes électriques, que ce soit pour votre domicile ou votre entreprise. Nous avons l'expertise et les connaissances nécessaires pour identifier et résoudre tous les types de problèmes électriques, qu'il s'agisse d'une panne de courant, d'un court-circuit ou d'une surcharge électrique. Notre équipe de professionnels est également équipée pour effectuer des réparations et des remplacements de composants électriques, tels que les interrupteurs, les disjoncteurs et les prises électriques. Nous nous engageons à fournir des solutions efficaces et durables pour tous vos besoins en matière de dépannage électrique. Nous comprenons que les pannes électriques peuvent survenir à tout moment, c'est pourquoi nous offrons un service de dépannage électrique d'urgence pour répondre à vos besoins en cas d'urgence. Nos électriciens sont disponibles 24h/24 et 7j/7 pour vous aider à résoudre rapidement les problèmes électriques dans votre maison ou votre entreprise. Chez Elewatt, la sécurité de nos clients est notre priorité absolue. Nous utilisons uniquement des équipements et des matériaux de qualité pour garantir la sécurité et la fiabilité de nos installations électriques. Nous respectons les normes de sécurité en vigueur pour garantir la sécurité de nos clients et de leurs biens. Enfin, nous offrons des services de maintenance électrique préventive pour aider nos clients à prévenir les problèmes électriques avant qu'ils ne surviennent. Nous proposons des inspections régulières pour détecter tout problème potentiel et effectuer les réparations nécessaires avant qu'ils ne deviennent des problèmes majeurs. En conclusion, si vous avez besoin d'un service de dépannage électrique rapide et efficace dans les zones de Bruxelles et Brabant Wallon, Elewatt est là pour vous aider. Nous offrons des services de qualité supérieure à un prix abordable. Contactez-nous dès aujourd'hui pour découvrir comment nous pouvons vous aider à résoudre vos problèmes électriques. ",
  },
  {
    title: "Nos dépannages électrique à Bruxelles",
    content: "Vous cherchez un électricien fiable pour un dépannage électrique à Bruxelles ? Ne cherchez plus, Elewatt est là pour vous aider ! Nous sommes spécialisés dans tous les types de dépannages électriques pour les particuliers et les entreprises à Bruxelles. Notre équipe d'experts en électricité est disponible 24 heures sur 24 et 7 jours sur 7 pour répondre à vos demandes en cas d'urgence. Nous comprenons que les pannes électriques peuvent être stressantes et même dangereuses, c'est pourquoi nous intervenons rapidement et efficacement pour résoudre tous vos problèmes électriques. Nos électriciens professionnels sont formés pour diagnostiquer et réparer toutes sortes de pannes électriques, qu'il s'agisse de problèmes de câblage, de court-circuits, de fusibles grillés, de prises défectueuses ou d'autres problèmes électriques. En choisissant Elewatt pour votre dépannage électrique à Bruxelles, vous pouvez être assuré que nous utiliserons des techniques et des outils de pointe pour garantir la sécurité et la fiabilité de vos installations électriques. Nous sommes également fiers d'offrir des prix compétitifs et transparents, ainsi que des devis gratuits pour tous nos services. En plus de notre service de dépannage électrique, nous offrons également des services d'installation électrique, de mise en conformité électrique, d'installation d'éclairage et plus encore. Nous sommes votre partenaire de confiance pour tous vos besoins en électricité à Bruxelles. N'hésitez pas à nous contacter dès maintenant pour un dépannage électrique rapide et efficace à Bruxelles. Nous sommes là pour vous aider !",
  },
   {
    title: "Nos dépannages électrique dans le Barabant-Wallon",
    content: "Vous êtes à la recherche d'un service de dépannage électrique rapide et efficace dans le Brabant Wallon ? Elewatt est l'entreprise d'électricité de confiance pour tous vos besoins de dépannage électrique. Nous avons une équipe d'électriciens qualifiés et expérimentés qui sont prêts à intervenir à tout moment, de jour comme de nuit, pour résoudre vos problèmes électriques. Notre entreprise est spécialisée dans les services de dépannage électrique pour les particuliers, les entreprises et les institutions publiques. Nous sommes capables d'identifier rapidement la source de vos problèmes électriques, de vous proposer des solutions efficaces et durables, et de les mettre en œuvre rapidement et en toute sécurité. Nous sommes à votre disposition pour tout type de dépannage électrique, que ce soit pour une panne de courant, une surtension électrique, un court-circuit, une panne de chauffage électrique, une panne de luminaire, un disjoncteur défaillant, un interrupteur qui ne fonctionne plus, ou tout autre problème électrique. Nous sommes également en mesure de réaliser des diagnostics électriques complets pour vous assurer une sécurité optimale de votre installation électrique. Notre équipe d'électriciens est formée aux dernières technologies et techniques en matière de dépannage électrique, ce qui nous permet de résoudre rapidement et efficacement tous les problèmes électriques. Nous utilisons des équipements de pointe pour identifier les problèmes électriques, ce qui nous permet de gagner du temps et de réduire les coûts pour nos clients. Chez Elewatt, nous sommes fiers de notre service clientèle de qualité supérieure. Nous sommes disponibles 24 heures sur 24 et 7 jours sur 7 pour répondre à vos demandes de dépannage électrique dans le Brabant Wallon. Nous sommes également en mesure de vous proposer des contrats de maintenance électrique pour assurer la sécurité et le bon fonctionnement de votre installation électrique à long terme. Contactez-nous dès maintenant pour un service de dépannage électrique rapide et efficace dans le Brabant Wallon.",
  },
];

export default function Depannages() {
  return (
    <ElectricPageTemplate
      title="Dépannages électrique"
      subtitle="Dépannage électrique rapide et efficace"
      description="Appelez-nous 24h/7j pour toutes interventions en dépannages électricité"
      bgImage={depannageImage}
      accordionData={depannageFaqData}
    />
  );
}
