import React from "react";
import ElectricPageTemplate from "./ElectricPageTemplate";
import depannageImage from "../assets/wire.webp";

const eclairageFaqData = [
  {
    title: "Installation d'éclairage électrique avec Electricien Rapide",
    content: "L'installation d'éclairage est un élément important de tout bâtiment, qu'il s'agisse d'une maison, d'un bureau ou d'un magasin. Elle permet de créer une ambiance agréable et de mettre en valeur les espaces intérieurs et extérieurs. Chez Electricien Rapide, nous offrons des services professionnels d'installation d'éclairage pour répondre à vos besoins spécifiques. Nous avons une équipe d'électriciens qualifiés qui sont spécialisés dans l'installation d'éclairage pour les bâtiments résidentiels, commerciaux et industriels. Nous travaillons avec nos clients pour comprendre leurs besoins et leurs préférences en matière d'éclairage, et nous leur proposons des solutions personnalisées pour répondre à leurs besoins. Que vous cherchiez à installer de nouveaux éclairages pour votre maison, votre bureau ou votre magasin, nous pouvons vous aider. Nous avons une large gamme d'options d'éclairage pour répondre à tous les besoins et à tous les budgets. Nos électriciens qualifiés installeront vos nouveaux luminaires avec précision et professionnalisme pour garantir une installation sûre et efficace. Nous sommes également spécialisés dans l'installation de systèmes d'éclairage extérieur. Que vous cherchiez à éclairer votre jardin, votre terrasse ou votre allée, nous pouvons vous aider à créer une ambiance agréable dans votre espace extérieur. Nous utilisons des équipements de qualité pour garantir que votre système d'éclairage extérieur est durable et résistant aux intempéries. Chez Electricien Rapide, nous sommes fiers de fournir un service de qualité supérieure à nos clients. Nous sommes équipés des dernières technologies pour garantir la sécurité et la fiabilité de nos installations d'éclairage. Nous utilisons également des matériaux et des équipements de qualité pour garantir la durabilité et la longévité de nos installations. Nous comprenons que chaque client a des besoins et des préférences différents en matière d'éclairage. C'est pourquoi nous travaillons en étroite collaboration avec nos clients pour créer des solutions d'éclairage personnalisées qui répondent à leurs besoins spécifiques. Nous sommes également disponibles pour répondre à toutes les questions que vous pourriez avoir sur l'installation d'éclairage. En conclusion, si vous cherchez des services d'installation d'éclairage dans les zones de Bruxelles et Brabant Wallon, Electricien Rapide est là pour vous aider. Nous sommes fiers de fournir un service de qualité supérieure à un prix abordable. Contactez-nous dès aujourd'hui pour découvrir comment nous pouvons vous aider à créer l'éclairage parfait pour votre maison, votre bureau ou votre magasin. ",
  },
  {
    title: "Nos installations d'éclairages électriques à Bruxelles",
    content: "Vous cherchez un électricien professionnel pour installer ou réparer les éclairages électriques de votre maison, appartement ou entreprise à Bruxelles ? Electricien Rapide est votre solution idéale. Notre entreprise propose des services complets pour toutes les installations d'éclairages électriques. Nous pouvons installer des éclairages intérieurs et extérieurs, des spots encastrés, des luminaires suspendus, des projecteurs et bien plus encore. Nous pouvons également vous conseiller sur les dernières tendances en matière d'éclairage et vous aider à trouver la solution la plus efficace et économe en énergie pour votre propriété. En plus de l'installation, nous offrons également des services de réparation pour les éclairages électriques défectueux. Nous avons une grande expérience dans la détection et la réparation des pannes électriques pour tous types d'éclairages. Notre équipe d'électriciens qualifiés est à votre disposition pour répondre à tous vos besoins en matière d'éclairage électrique à Bruxelles. Nous garantissons une installation rapide, efficace et professionnelle pour que vous puissiez profiter de votre nouvel éclairage dès que possible. Contactez-nous dès maintenant pour obtenir un devis gratuit pour votre projet d'éclairage électrique à Bruxelles. Nous sommes impatients de travailler avec vous pour réaliser votre vision d'éclairage personnalisée.",
  },
  {
    title: "Nos installations d'éclairages électriques dans le Barabant-Wallon",
    content: "Vous recherchez un électricien qualifié pour installer des éclairages dans le Brabant Wallon ? Ne cherchez pas plus loin que Electricien Rapide, votre partenaire électricien de confiance. Chez Electricien Rapide, nous sommes spécialisés dans l'installation d'éclairages électriques pour les propriétaires de maisons et d'entreprises dans le Brabant Wallon. Que vous ayez besoin d'éclairages intérieurs ou extérieurs, nous pouvons vous aider à trouver les solutions les plus adaptées à vos besoins. Nous offrons un large choix d'options d'éclairage, y compris les luminaires encastrés, les appliques murales, les suspensions, les spots et bien plus encore. Nos électriciens professionnels peuvent vous aider à sélectionner les produits les plus adaptés à votre espace et à votre budget. Notre équipe de professionnels expérimentés et qualifiés se tient prête à vous fournir des services d'installation d'éclairage de haute qualité dans le Brabant Wallon. Nous sommes fiers de notre service client exceptionnel et nous nous engageons à fournir des résultats à la hauteur de vos attentes. Nous offrons également des services de maintenance et de réparation pour garantir que vos éclairages fonctionnent toujours correctement. Si vous avez besoin d'un dépannage, notre équipe d'experts est disponible pour résoudre rapidement et efficacement tout problème d'éclairage. Faites confiance à Electricien Rapide pour tous vos besoins en matière d'installation d'éclairages électriques dans le Brabant Wallon. Contactez-nous dès maintenant pour en savoir plus sur nos services et pour planifier une consultation.",
  },
];

export default function InstallationEclairage() {
  return (
    <ElectricPageTemplate
      title="INSTALLATION D'ECLAIRAGE"
      subtitle="Installation d'éclairage électrique"
      description="Appelez-nous pour votre installation d'éclairage électrique."
      bgImage={depannageImage}
      accordionData={eclairageFaqData}
    />
  );
}
