import React from "react";
import ElectricPageTemplate from "./ElectricPageTemplate";
import depannageImage from "../assets/inst.webp"; // adjust path

const depannageFaqData = [
  {
    title: "Mise en conformité électrique avec Elewatt",
    content: "La mise en conformité électrique est une étape importante pour garantir la sécurité et le bon fonctionnement de votre système électrique. Elle consiste à vérifier que toutes les installations électriques de votre bâtiment répondent aux normes en vigueur en matière de sécurité électrique.  Chez Elewatt, nous proposons des services de mise en conformité électrique pour vous aider à vous assurer que votre système électrique est conforme aux normes en vigueur. Nous avons une équipe d'électriciens qualifiés qui ont une vaste expérience dans la réalisation de ces travaux.La mise en conformité électrique est une étape cruciale pour les propriétaires d'entreprises et de maisons qui cherchent à améliorer la sécurité de leur bâtiment. Elle permet de s'assurer que les installations électriques répondent aux normes de sécurité en vigueur et qu'elles sont adaptées à l'utilisation prévue.  Chez Elewatt, nous offrons une gamme complète de services de mise en conformité électrique pour garantir que votre système électrique est en conformité avec les normes en vigueur. Nous vérifions tous les aspects de votre système électrique, y compris le câblage, les disjoncteurs, les prises et les interrupteurs, pour nous assurer qu'ils répondent aux normes en vigueur. Nous travaillons en étroite collaboration avec nos clients pour comprendre leurs besoins et leurs exigences en matière de mise en conformité électrique. Nous proposons des solutions adaptées à leurs besoins spécifiques pour garantir que leur système électrique est en conformité avec les normes en vigueur.Chez Elewatt, nous sommes fiers de fournir un service de qualité supérieure à un prix abordable. Nous sommes équipés des dernières technologies pour garantir la sécurité et la fiabilité de nos travaux de mise en conformité électrique. Nous utilisons uniquement des équipements et des matériaux de qualité pour garantir la durabilité et la longévité de nos installations. Nous sommes également disponibles pour vous aider en cas d'urgence électrique. Si vous rencontrez des problèmes électriques, notre équipe d'électriciens qualifiés est disponible 24 heures sur 24 et 7 jours sur 7 pour vous aider. Nous sommes fiers de fournir des services de qualité supérieure à nos clients, quelle que soit leur situation. En conclusion, si vous cherchez des services de mise en conformité électrique dans les zones de Bruxelles et Brabant Wallon, Elewatt est là pour vous aider. Nous sommes fiers de fournir un service de qualité supérieure à un prix abordable. Contactez-nous dès aujourd'hui pour découvrir comment nous pouvons vous aider à garantir la sécurité et le bon fonctionnement de votre système électrique.  ",
  },
  {
    title: "Nos mise en conformité électrique à Bruxelles",
    content: "Chez Elewatt, nous sommes spécialisés dans les mises en conformité électrique à Bruxelles. Nous comprenons l'importance de la sécurité électrique pour votre maison ou votre entreprise, c'est pourquoi nous nous assurons que tous nos travaux sont effectués selon les normes de sécurité électrique les plus strictes. Notre équipe d'électriciens qualifiés dispose de l'expertise nécessaire pour effectuer des inspections approfondies de votre installation électrique et identifier les problèmes qui pourraient nuire à votre sécurité électrique. Nous proposons ensuite des solutions personnalisées pour corriger les problèmes et assurer la conformité aux normes électriques. Nous sommes en mesure d'intervenir rapidement pour les mises en conformité électrique d'urgence ou les projets de plus grande envergure. Nous fournissons également des conseils professionnels pour vous aider à prendre des décisions éclairées en matière de sécurité électrique. Contactez-nous dès maintenant pour obtenir plus d'informations sur nos services de mise en conformité électrique à Bruxelles. Chez Elewatt, nous nous engageons à garantir la sécurité électrique de nos clients et à leur offrir une tranquillité d'esprit totale.",
  },
   {
    title: "Nos mise en conformité électrique dans le Barabant-Wallon",
    content: "Chez Elewatt, nous sommes spécialisés dans les mises en conformité électrique pour les habitations et les entreprises situées dans le Brabant Wallon. Nous comprenons l'importance d'avoir des installations électriques sûres et conformes aux normes en vigueur pour garantir la sécurité de votre domicile ou de votre entreprise. Nos électriciens qualifiés sont en mesure de diagnostiquer les éventuels problèmes électriques et de proposer des solutions pour les résoudre. Nous intervenons dans le respect des normes de sécurité et des règles en vigueur dans le Brabant Wallon. Nous réalisons une étude de votre installation électrique et nous proposons des solutions adaptées pour mettre votre installation en conformité. Nous prenons en compte toutes les normes et les règles liées à votre installation, que ce soit pour une maison ou pour une entreprise. Chez Elewatt, nous sommes conscients de l'importance d'avoir une installation électrique sûre et fonctionnelle. Nous pouvons vous aider à mettre en conformité votre installation électrique en vous proposant des solutions sur mesure et adaptées à vos besoins. Nous pouvons également vous aider à identifier les risques potentiels liés à votre installation électrique et vous proposer des solutions pour les résoudre. Nos électriciens sont des professionnels qualifiés, formés pour travailler avec les normes et les règles en vigueur dans le Brabant Wallon. Ils sont à votre disposition pour répondre à toutes vos questions et vous aider à mettre en conformité votre installation électrique. Nous sommes à votre disposition pour vous aider à résoudre tous vos problèmes électriques et pour vous offrir une installation électrique sûre et conforme aux normes en vigueur dans le Brabant Wallon. N'hésitez pas à nous contacter pour toute demande de mise en conformité électrique dans le Brabant Wallon. Nous sommes à votre disposition pour vous aider et pour vous offrir une installation électrique sûre et fonctionnelle.",
  },
];

export default function Depannages() {
  return (
    <ElectricPageTemplate
  title="MISE EN CONFORMITE"
  subtitle="Mise en conformité électrique"
  description="Appelez-nous pour votre mise en conformité électrique"
  bgImage={depannageImage}

   accordionData={depannageFaqData}
/>
    
  );
}
